# Generated by Django 5.2.8 on 2025-11-18 06:35

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_product_extra_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('delivery_address', models.TextField(max_length=400)),
                ('amount_paid', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date_ordered', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processing', 'در حال آماده سازی سفارش'), ('On The Way', 'تحویل پیک موتوری داده شد'), ('Delivered', 'تحویل مشتری داده شد'), ('canceled', 'سفارش لغو شده است')], default='Pending')),
                ('last_update', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
