# Generated by Django 5.2.8 on 2025-11-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم های داخل سفارش', 'verbose_name_plural': 'آیتم های داخل سفارشات'},
        ),
    ]
