# Generated by Django 5.2.8 on 2025-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userdeliveryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_description',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
