# Generated by Django 5.2.8 on 2025-11-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_extra_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_address', models.TextField(max_length=1000)),
                ('shop_email_1', models.EmailField(max_length=100)),
                ('shop_email_2', models.EmailField(blank=True, max_length=100)),
                ('shop_phone_1', models.CharField(max_length=25)),
                ('shop_phone_2', models.CharField(blank=True, max_length=25)),
                ('shop_phone_3', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='userdeliveryinfo',
            options={'verbose_name': 'مشخصات ارسال سفارش مشتری', 'verbose_name_plural': 'مشخضات ارسال سفارش مشتریان'},
        ),
    ]
