# Generated by Django 5.2.8 on 2025-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shopinfo_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'verbose_name': 'اطلاعات فروشگاه', 'verbose_name_plural': 'اطلاعات فروشگاه'},
        ),
        migrations.AddField(
            model_name='userdeliveryinfo',
            name='delivery_method',
            field=models.CharField(choices=[('post', 'ارسال با پست'), ('peyk', 'پیک موتوری')], max_length=20, null=True),
        ),
    ]
