# Generated by Django 5.2.8 on 2025-11-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_shopinfo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeliveryinfo',
            old_name='state',
            new_name='province',
        ),
        migrations.AddField(
            model_name='userdeliveryinfo',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
