# Generated by Django 5.2.8 on 2025-11-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_state_userdeliveryinfo_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeliveryinfo',
            name='delivery_method',
            field=models.CharField(choices=[('post', 'ارسال با پست'), ('peyk', 'ارسال با پیک')], max_length=20, null=True),
        ),
    ]
